### ISSUE TITLE
DLL load failed while importing _framework_bindings: 动态链接库(DLL)初始化例程失败。

### ISSUE THREAD

**Issue by mwh666** [dirkzon/gesture-recognition#1]
After I ran gesture.py, the following problems occurred:

Traceback (most recent call last):

  File D:\Anaconda\Lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\users\69138\desktop\gesture-recognition-master\gesture.py:5
    from mediapipe.python.solutions import drawing_utils, hands

  File ~\AppData\Roaming\Python\Python312\site-packages\mediapipe\__init__.py:15
    from mediapipe.python import *

  File ~\AppData\Roaming\Python\Python312\site-packages\mediapipe\python\__init__.py:17
    from mediapipe.python._framework_bindings import model_ckpt_util

ImportError: DLL load failed while importing _framework_bindings: 动态链接库(DLL)初始化例程失败。

Why is this? How should I solve it? I can't find the answer.

**Comment by mwh666** [comment]
I have found a solution to this problem. I created a new Anaconda environment and imported the libraries from the requirements.txt file into it, and now it can run in this environment.

**Comment by dirkzon** [comment]
I've edited the README to explain how to install all the requirement.txt packages and start the gesture.py script within a virtual environment.
